# Generated by Django 5.0.2 on 2024-02-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
